/**
 * HRApp
 * HR Database Application
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bart00@hitachi-id.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

'use strict';
import * as models from './';

export interface Person {
    

    id?: string;

    first_name?: string;

    last_name?: string;

    department?: models.Department;

    location?: models.Location;

    managers?: models.Person;

    /**
     * Personnel status
     */
    status?: Person.StatusEnum;

    hire_date?: Date;

    term_date?: Date;

    /**
     * Effective date of change
     */
    effective_date?: Date;
}
export namespace Person {

    export enum StatusEnum { 
        Active = <any> 'Active',
        On_Leave = <any> 'On Leave',
        Terminated = <any> 'Terminated',
    }
}
